version: '3.8'

services:
  app:
    build:
      context: .
    container_name: app
    working_dir: /app
    volumes:
      - ./:/app
      - ./.m2:/root/.m2
    command: sh run.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/todoApp
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
      - "35729:35729"
      - "5005:5005"
    depends_on:
      - db

  db:
    image: postgres:15.6
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todoApp
    ports:
      - "5432:5432"