CREATE TABLE IF NOT EXISTS user_account (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   created_by BIGINT,
   last_modified_by BIGINT,
   firstname VARCHAR(255),
   lastname VARCHAR(255),
   email VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   role VARCHAR(255) NOT NULL,
   CONSTRAINT pk_useraccount PRIMARY KEY (id)
);

ALTER TABLE user_account ADD CONSTRAINT uc_useraccount_email UNIQUE (email);

CREATE TABLE IF NOT EXISTS token (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   token VARCHAR(255),
   token_type VARCHAR(255),
   revoked BOOLEAN NOT NULL,
   expired BOOLEAN NOT NULL,
   user_id BIGINT,
   CONSTRAINT pk_token PRIMARY KEY (id)
);

ALTER TABLE token ADD CONSTRAINT uc_token_token UNIQUE (token);

ALTER TABLE token ADD CONSTRAINT FK_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES user_account (id);

CREATE TABLE IF NOT EXISTS to_do_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   created_by BIGINT,
   last_modified_by BIGINT,
   name VARCHAR(255) NOT NULL,
   CONSTRAINT pk_todorecord PRIMARY KEY (id)
);
